### ISSUE TITLE
【内容勘误】不可不知的项目冷知识/如何在登录后所有的请求的header中加入cookie

### ISSUE THREAD

**Issue by pengzhanbo** [qdleader/qdleader#37]
[不可不知的项目冷知识/如何在登录后所有的请求的header中加入cookie.md](https://github.com/qdleader/qdleader/blob/master/%E4%B8%8D%E5%8F%AF%E4%B8%8D%E7%9F%A5%E7%9A%84%E9%A1%B9%E7%9B%AE%E5%86%B7%E7%9F%A5%E8%AF%86/%E5%A6%82%E4%BD%95%E5%9C%A8%E7%99%BB%E5%BD%95%E5%90%8E%E6%89%80%E6%9C%89%E7%9A%84%E8%AF%B7%E6%B1%82%E7%9A%84header%E4%B8%AD%E5%8A%A0%E5%85%A5cookie.md)

虽然这篇文章是三年前的，但是希望作者应该对其内容进行更新修改其中的错误内容。避免导致错误的引导。

`withCredentials ` 这个值，其作用是，在进行跨域请求时，允许服务器对其自己的域设置 cookies。文档： [MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest/withCredentials)

而且 `withCredentials` **永远不会影响到同源请求**，它反而是在跨域请求中，对支持跨域请求的请求生效。

**Comment by qdleader** [comment]
thanks
